CREATE TABLE vehicles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          vin VARCHAR(17) NOT NULL,
                          license_plate VARCHAR(20) NOT NULL,
                          make VARCHAR(100) NOT NULL,
                          model VARCHAR(100) NOT NULL,
                          manufacture_year INTEGER NOT NULL,
                          status VARCHAR(30) NOT NULL,

                          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          version BIGINT NOT NULL DEFAULT 0,

                          CONSTRAINT uk_vehicles_vin UNIQUE (vin),
                          CONSTRAINT uk_vehicles_license_plate UNIQUE (license_plate),

                          CONSTRAINT chk_vehicles_manufacture_year
                              CHECK (manufacture_year >= 1886),

                          CONSTRAINT chk_vehicles_status
                              CHECK (
                                  status IN (
                                             'ACTIVE',
                                             'IN_MAINTENANCE',
                                             'OUT_OF_SERVICE',
                                             'RETIRED'
                                      )
                                  )
);


CREATE TABLE drivers (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         first_name VARCHAR(100) NOT NULL,
                         last_name VARCHAR(100) NOT NULL,

                         license_number VARCHAR(50) NOT NULL,
                         license_category VARCHAR(20) NOT NULL,
                         license_expiry_date DATE NOT NULL,

                         phone VARCHAR(30),
                         email VARCHAR(255),

                         status VARCHAR(30) NOT NULL,

                         created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         version BIGINT NOT NULL DEFAULT 0,

                         CONSTRAINT uk_drivers_license_number
                             UNIQUE (license_number),

                         CONSTRAINT chk_drivers_status
                             CHECK (
                                 status IN (
                                            'ACTIVE',
                                            'INACTIVE',
                                            'SUSPENDED'
                                     )
                                 )
);


CREATE TABLE vehicle_assignments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     vehicle_id BIGINT NOT NULL,
                                     driver_id BIGINT NOT NULL,

                                     assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     unassigned_at TIMESTAMPTZ,

                                     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_vehicle_assignments_vehicle
                                         FOREIGN KEY (vehicle_id)
                                             REFERENCES vehicles(id)
                                             ON DELETE RESTRICT,

                                     CONSTRAINT fk_vehicle_assignments_driver
                                         FOREIGN KEY (driver_id)
                                             REFERENCES drivers(id)
                                             ON DELETE RESTRICT,

                                     CONSTRAINT chk_vehicle_assignment_dates
                                         CHECK (
                                             unassigned_at IS NULL
                                                 OR unassigned_at >= assigned_at
                                             )
);


CREATE TABLE maintenance_records (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     vehicle_id BIGINT NOT NULL,

                                     maintenance_type VARCHAR(50) NOT NULL,
                                     description VARCHAR(1000),

                                     service_date DATE NOT NULL,
                                     next_service_date DATE,

                                     odometer BIGINT,
                                     cost NUMERIC(12, 2),

                                     status VARCHAR(30) NOT NULL,

                                     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_maintenance_vehicle
                                         FOREIGN KEY (vehicle_id)
                                             REFERENCES vehicles(id)
                                             ON DELETE RESTRICT,

                                     CONSTRAINT chk_maintenance_status
                                         CHECK (
                                             status IN (
                                                        'SCHEDULED',
                                                        'IN_PROGRESS',
                                                        'COMPLETED',
                                                        'CANCELLED'
                                                 )
                                             ),

                                     CONSTRAINT chk_maintenance_odometer
                                         CHECK (
                                             odometer IS NULL
                                                 OR odometer >= 0
                                             ),

                                     CONSTRAINT chk_maintenance_cost
                                         CHECK (
                                             cost IS NULL
                                                 OR cost >= 0
                                             ),

                                     CONSTRAINT chk_maintenance_dates
                                         CHECK (
                                             next_service_date IS NULL
                                                 OR next_service_date >= service_date
                                             )
);


CREATE TABLE vehicle_locations (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   vehicle_id BIGINT NOT NULL,

                                   latitude NUMERIC(9, 6) NOT NULL,
                                   longitude NUMERIC(9, 6) NOT NULL,

                                   speed NUMERIC(8, 2),
                                   heading NUMERIC(6, 2),

                                   recorded_at TIMESTAMPTZ NOT NULL,

                                   created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_vehicle_locations_vehicle
                                       FOREIGN KEY (vehicle_id)
                                           REFERENCES vehicles(id)
                                           ON DELETE RESTRICT,

                                   CONSTRAINT chk_vehicle_location_latitude
                                       CHECK (
                                           latitude BETWEEN -90 AND 90
                                           ),

                                   CONSTRAINT chk_vehicle_location_longitude
                                       CHECK (
                                           longitude BETWEEN -180 AND 180
                                           ),

                                   CONSTRAINT chk_vehicle_location_speed
                                       CHECK (
                                           speed IS NULL
                                               OR speed >= 0
                                           ),

                                   CONSTRAINT chk_vehicle_location_heading
                                       CHECK (
                                           heading IS NULL
                                               OR heading BETWEEN 0 AND 360
                                           )
);