CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           username VARCHAR(100) NOT NULL,
                           email VARCHAR(255) NOT NULL,
                           password_hash VARCHAR(255) NOT NULL,

                           enabled BOOLEAN NOT NULL DEFAULT TRUE,

                           created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           version BIGINT NOT NULL DEFAULT 0,

                           CONSTRAINT uk_app_users_username UNIQUE (username),
                           CONSTRAINT uk_app_users_email UNIQUE (email)
);


CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       name VARCHAR(50) NOT NULL,

                       CONSTRAINT uk_roles_name UNIQUE (name),

                       CONSTRAINT chk_roles_name
                           CHECK (
                               name IN (
                                        'ADMIN',
                                        'FLEET_MANAGER'
                                   )
                               )
);


CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,

                            PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES app_users(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES roles(id)
                                    ON DELETE RESTRICT
);


CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id);


INSERT INTO roles (name)
VALUES
    ('ADMIN'),
    ('FLEET_MANAGER');